// packages/tic-tac-mobx/src/components/square/Square.tsx
import React from 'react';
import { observer } from 'mobx-react-lite';

export type SquareItem = { index: string, value: string };

type Props = {
  onClick: (item: SquareItem) => void;
  item: SquareItem;
}

export const Square = observer<Props>(({ onClick, item }) => {
  const emitOnClick = () => {
    onClick(item);
  };
  console.log('[Render]', item.index);
  return <div className="square" onClick={emitOnClick}>{item.value}</div>;
});

// packages/tic-tac-vue/src/components/Square.vue
<script lang="ts">
import Vue from 'vue'
import { SquareItem } from 'common'

export default Vue.extend({
  props: {
    item: Object as () => SquareItem
  },

  render (createElement) {
    console.log('[Render]', this.item.index)
    return createElement('div', {
      staticClass: 'square',
      on: {
        click: () => {
          this.$emit('square-click', this.item)
        }
      }
    }, this.item.value)
  }
})
</script>
